version: '2'

services:
  storage:
    image: openzipkin/zipkin-mysql:1.39.3
    container_name: mysql
    ports:
      - 3306:3306
  query:
    image: openzipkin/zipkin-java:0.11.0
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=mysql
    ports:
      # Listen port for the Scribe transport
      - 9410:9410
      # Historical port used for the Zipkin HTTP Api
      - 9411:9411
      # Zipkin UI used to be on a separate process listening on port 8080
      - 8080:9411
    depends_on:
      - storage
