storage:
  image: openzipkin/zipkin-mysql:1.39.0
  container_name: mysql
  ports:
    - 3306:3306
query:
  image: openzipkin/zipkin-java:0.10.4
  environment:
    - STORAGE_TYPE=mysql
    - MYSQL_HOST=mysql
    - MYSQL_PORT=3306
  ports:
    # Historical port used for the Zipkin HTTP Api
    - 9411:9411
    # Zipkin UI used to be on a separate process listening on port 8080
    - 8080:9411
  links:
    - storage
